# Applies a custom Tailwind CSS v4 theme to a Rails 8 app.
# Overwrites the default application.tailwind.css generated by tailwind-rails
# with a preset @theme containing custom colors, fonts, and animations.

say "Applying custom Tailwind CSS theme...", :cyan

tailwind_css = <<~CSS
  @import "tailwindcss";

  @theme {
    --color-ivory-50: #fefdfb;
    --color-ivory-100: #fdf9f3;
    --color-ivory-200: #faf2e7;
    --color-ivory-300: #f6e8d7;
    --color-ivory-400: #f0d9c3;
    --color-ivory-500: #e8c7a6;
    --color-ivory-600: #d4a574;
    --color-ivory-700: #b8834a;
    --color-ivory-800: #8f6238;
    --color-ivory-900: #6b4a2a;

    --color-pastel-pink: #f8d7da;
    --color-pastel-lavender: #e2d5f1;
    --color-pastel-mint: #d1f2eb;
    --color-pastel-peach: #fdebd0;
    --color-pastel-sky: #cce7ff;
    --color-pastel-sage: #e8f5e8;

    --font-sans: 'Inter var', ui-sans-serif, system-ui, sans-serif;

    --animate-fade-in: fadeIn 0.5s ease-in-out;
    --animate-slide-up: slideUp 0.3s ease-out;
  }

  @keyframes fadeIn {
    0% { opacity: 0; }
    100% { opacity: 1; }
  }

  @keyframes slideUp {
    0% { transform: translateY(10px); opacity: 0; }
    100% { transform: translateY(0); opacity: 1; }
  }
CSS

create_file "app/assets/stylesheets/application.tailwind.css", tailwind_css, force: true

say "Tailwind theme applied to app/assets/stylesheets/application.tailwind.css.", :green
say "\nSetup complete.", :blue
